def generate_report(
    target,
    result,
    risk,
    details
):

    report = f"""
PHISHSHIELD AI SECURITY REPORT

Target:
{target}

Detection Result:
{result}

Risk Score:
{risk}

Threat Details:
{details}

Generated by:
PhishShield AI
"""

    return report