"""Text reports that preserve observed evidence and explicitly label unavailable sources."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def _section(title: str, value: Any) -> list[str]:
    lines = ["", title]
    if value is None:
        return lines + ["Unavailable", "Reason: source was not configured or did not return a result."]
    if isinstance(value, dict):
        for key, item in value.items():
            if key in {"html"}:
                continue
            lines.append(f"{key}: {item if item is not None else 'Unavailable'}")
        return lines
    return lines + [str(value)]


def generate_report(target, result, risk, details, *, confidence=None, risk_level=None, brand=None,
                    ssl=None, whois=None, virustotal=None, scan_type="URL", dns=None, mitre=None,
                    website=None, extracted_urls=None, recommendation=None, source_errors=None, providers=None):
    lines = ["PHISHSHIELD AI SECURITY REPORT", f"Generated: {datetime.now(timezone.utc).isoformat()}",
             f"Analysis type: {scan_type}", f"Input: {target}", f"Detection result: {result}",
             f"ML confidence: {confidence if confidence is not None else 'Unavailable'}",
             f"Risk score: {risk if risk is not None else 'Unavailable'}", f"Risk level: {risk_level or 'Unavailable'}",
             f"Brand intelligence: {brand or 'Unavailable'}", "", "Threat details:", details or "No threat details available."]
    lines += _section("TLS/SSL", ssl)
    lines += _section("WHOIS", whois)
    lines += _section("DNS", dns)
    lines += _section("VirusTotal", virustotal)
    lines += _section("Normalized provider evidence", providers)
    lines += _section("MITRE ATT&CK analytical mapping", mitre if mitre else None)
    lines += _section("Website analysis", website)
    if extracted_urls is not None:
        lines += _section("Extracted URLs", extracted_urls)
    if recommendation:
        lines += ["", "Recommendation", recommendation]
    if source_errors:
        lines += _section("Source availability/errors", source_errors)
    lines += ["", "Generated by PhishShield AI"]
    return "\n".join(lines)


def generate_canonical_report(scan_type: str, analysis: dict) -> str:
    """Report the exact canonical result and every provider/local evidence object."""
    website = analysis.get("website")
    if isinstance(website, dict): website = {k: v for k, v in website.items() if k != "html"}
    return generate_report(analysis.get("normalized_url") or analysis.get("url"), analysis.get("verdict"), analysis.get("risk"),
        "\n".join(analysis.get("reasons", [])), confidence=analysis.get("confidence_strength"), risk_level=analysis.get("risk_level"),
        brand=analysis.get("brand"), ssl=analysis.get("tls"), whois=analysis.get("whois"), dns=analysis.get("dns"),
        virustotal=analysis.get("virustotal"), providers=analysis.get("providers"), mitre=analysis.get("mitre"), website=website,
        recommendation=analysis.get("recommendation"), scan_type=scan_type)


def generate_input_report(scan_type: str, target: str, context: dict, url_analyses: list[dict]) -> str:
    """Report OCR/email context separately from the canonical verdict per URL."""
    lines = ["PHISHSHIELD AI SECURITY REPORT", f"Generated: {datetime.now(timezone.utc).isoformat()}",
             f"Analysis type: {scan_type}", f"Input: {target}", "Context evidence:", str(context),
             "", "Canonical URL analyses:"]
    if not url_analyses:
        lines.append("No URLs were extracted; no URL verdict was fabricated.")
    for analysis in url_analyses:
        website = analysis.get("website", {})
        if isinstance(website, dict): website = {key: value for key, value in website.items() if key != "html"}
        lines.extend(["", f"Normalized URL: {analysis.get('normalized_url') or analysis.get('url')}",
                      f"FINAL VERDICT: {analysis.get('verdict')}", f"Risk score: {analysis.get('risk')}",
                      f"Confidence/evidence strength: {analysis.get('confidence_strength')}",
                      "Why this verdict: " + "; ".join(analysis.get("reasons", [])),
                      "Provider evidence: " + str(analysis.get("providers", {})),
                      "DNS: " + str(analysis.get("dns", {})), "TLS: " + str(analysis.get("tls", {})),
                      "WHOIS/RDAP: " + str(analysis.get("whois", {})), "Website: " + str(website),
                      "Brand: " + str({"brand": analysis.get("brand"), "similarity": analysis.get("similarity")}),
                      "MITRE ATT&CK: " + str(analysis.get("mitre", [])),
                      "Copilot: " + str(analysis.get("ai_copilot", {}))])
    return "\n".join(lines)
